name: "Run Goose Migrations"

on:
  push:
    branches:
      - master  # Или твоя ветка

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Устанавливаем Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # Можно поменять на актуальную верси

      - name: Скачиваем и собираем goose
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Проверяем, работает ли goose
        run: |
          which goose || echo "goose не найден!"
          goose -version || echo "goose не запускается!"

      - name: Apply migrations
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          goose -dir=migrations postgres "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable" up




