name: "Run Goose Migrations"

on:
  push:
    branches:
      - master  # Или твоя ветка

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Remove old goose (если он есть)
        run: rm -f /usr/local/bin/goose || true

      - name: Download goose
        run: |
          curl -L https://github.com/pressly/goose/releases/download/v3.14.0/goose-linux-amd64 -o /usr/local/bin/goose
          chmod +x /usr/local/bin/goose
          ls -lah /usr/local/bin/goose  # Проверка, скачался ли бинарник

      - name: Проверяем скачался ли goose
        run: |
          ls -lah /usr/local/bin/goose
          file /usr/local/bin/goose
          which goose || echo "goose не найден!"
          goose -version || echo "goose не запускается!"

      - name: Apply migrations
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          goose -dir=migrations postgres "postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable" up

